### ISSUE TITLE
Async Requests

### ISSUE THREAD

**Issue by nateiorg** [knightzac19/PHP-ArkData#2]
Would it be more beneficial to just allow Steam requests to be pushed to a message queue? With 10 worker processes you could easily be pushing 1k/s, and it's incredibly easy to ramp that to more workers.

I'm considering using this for my own project, and if I do I was going to just implement a queue system into the Steam request portion anyway. If this is something that others would find useful I'd make a pull request. I'd provide the bash script for keeping worker processes alive, the worker script itself, etc. However, the Windows portion would not be included (sorry :P).

Do you know if there are any Steam limitations to concurrent requests from one IP?

**Comment by knightzac19** [comment]
I've actually put this particular library development on hold at the moment because I decided to make a node.js(https://github.com/knightzac19/NodeJS-ArkData) version of it. It works on everything behind the scenes and keeps all the player data up to  date.

However, as far as the steam part goes, you can only submit 100 steam IDs per request and 100,000 web-api requests per day. So putting them in a queue would probably not be beneficial as steam takes the IDs in batches already. Running them one at a time could eat up your 100,000 limit pretty quickly.

**Comment by nateiorg** [comment]
Oh I don't mean one at a time, I mean offloading batches of 100 to a Message Queue (think RabbitMQ - but RabbitMQ is not necessary). Message Queues are most often used in big data / high traffic scenarios, but would be perfect in this scenario.

Think of it this way: You have 10,000 Players and need to get all of them within a reasonable amount of time. You delegate 100 batches of 100 IDs to asynchronous worker processes, meaning you have 100 requests that are immediately processed, concurrently. 10,000 Player IDs from Steam in 1 second - all while using only 100 API requests.

**Comment by knightzac19** [comment]
That would definitely work, but I wouldn't expect it all in 1 second, steam's response is usually 1-2 seconds per 100 steam ids, sometimes longer on their busier days. You should probably put some server checks in there too because when steam community goes down, so does their web-api.

**Comment by nateiorg** [comment]
That's good to know. I'm kind of shocked their API goes down when the Community goes down. That seems a bit... Amateur?

That's cool you're working on getting this functionality in Node as well. Makes me wish I knew Node :D Thanks for the responses, hope all is going well in the Node project!

**Comment by knightzac19** [comment]
I've actually finished the Node side of things if you want to check it out, it's not too hard to read if you know any Javascript (same thing really). I'm actually working on porting over ASM(ark server manager) to Angular/Node.js/PHP and it'll use that same node.js library on the backend. It starts up in about 2.3s with ~320 people in my Ark folder. However, this is on a pretty beefy server with SSDs as well.

**Comment by TheRealAlexV** [comment]
You should contact Bletch over at http://arkservermanager.freeforums.net/. He's taken over development of ASM after the original creators became too busy to maintain it. I had actually just replied to a thread you posted over there [regarding a linux port of ASM](http://arkservermanager.freeforums.net/thread/1034/asm-linux-version). 

I'm a beta tester over there and the development team (really just Bletch and a super dedicated team of support staff and QA testers) would probably be pretty open to working with you. You should drop by and give us an update in that thread I posted!
